### ISSUE TITLE
No access to the pretrained-model

### ISSUE THREAD

**Issue by ManBehindTheMyth** [yinguobing/facial-landmark-detection-hrnet#11]
Hello author,

is it possible to gain access to the pre-trained model besides the pan.baidu link you have posted in the readme file?
Doesn't work if you are Greek (cant even create an account :P). Working on my thesis project! Thanks for your time

**Comment by yinguobing** [comment]
Hi @ManBehindTheMyth 

Please send me a mail. The coming holiday will take 6 days and I hope there is still time for me to send you the files.

**Comment by ManBehindTheMyth** [comment]
I sent you at yinguobing@gmail.com an email, Thanks a lot for your immidiate answer

**Comment by yinguobing** [comment]
File sent. Safe to close issue #11.
