### ISSUE TITLE
NME with original image dimensions

### ISSUE THREAD

**Issue by Sheepy0** [yinguobing/facial-landmark-detection-hrnet#15]
Hello,
Thank you @yinguobing for your work and blog, I am really enjoying them.

In the evaluation, before we compute NME, we to transform the marks back to the original image dimensions.
Do you know why the transform of the marks back to the original image dimensions is necessary for the NME ?

Thank you

**Comment by yinguobing** [comment]
Actually I didn't pay much attention to the NME computation. In the code the predictions are transformed back because the labels are of image dimensions. If the predictions won't be transformed, then we will have to transform the labels into the cropped image dimension.

**Comment by Sheepy0** [comment]
Great, this makes sense !
Also, at the moment, I think the NME computation is only being performed on a single image per batch, rather than on the entire batch.

Thanks for your quick response,
have a good day.
