### ISSUE TITLE
how to create dataset?

### ISSUE THREAD

**Issue by erickuang0** [yinguobing/facial-landmark-detection-hrnet#18]
Hello author, I'm having trouble with the "Set the training and testing datasets" step ,i didn't find any file call "wflw_train" & "wflw_train" in WFLW_images file?how can i create these two file ? Thank you.

**Comment by yinguobing** [comment]
Please follow the instructions of this link: https://github.com/yinguobing/facial-landmark-detection-hrnet#generate-the-training-data

**Comment by erickuang0** [comment]
Hello author,i already done generate-the-training-data" step but it only generate "wflw.record " file ,i didn't see any  "wflw_train" & "wflw_train" files?

**Comment by yinguobing** [comment]
WFLW provides train and test splits by itself. Try changing the init parameters here: 
https://github.com/yinguobing/face-mesh-generator/blob/a4722036f48044ae7bfe121383274b3218db18b1/fmd/wflw.py#L23

or, simply splits the training dataset into training and testing subsets.

**Comment by erickuang0** [comment]
Hello author, but i used "[Tsinghua National Laboratory](https://wywu.github.io/projects/LAB/WFLW.html)" link download dataset didn't see" train"&"test"  files. And i use "https://github.com/yinguobing/face-mesh-generator/blob/a4722036f48044ae7bfe121383274b3218db18b1/fmd/wflw.py#L23" method to split train & test dataset only got "list_98pt_rect_attr_test.txt" &"list_98pt_rect_attr_train.txt"files.

**Comment by erickuang0** [comment]
Hello author, I know why i can't get the correct train & test dataset,because i use wrong branch of "face-mesh-generator" so i can't generate the correct dataset. Thank for your help.
