### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by glmanhtu** [yinguobing/facial-landmark-detection-hrnet#5]
Hello @yinguobing 

It's me again,
I have found there is a problem in the implementation, when I was trying to train the network with the 300VW dataset, the following problem occurred:
`ValueError: could not broadcast input array from shape (19,19) into shape (20,19)`

It turned out that the problem appear in here: https://github.com/yinguobing/facial-landmark-detection-hrnet/blob/master/mark_operator.py#L112-L113

The int(<float number>) is not always do the same thing, as you can see in the debugging output below:
<img width="682" alt="Screenshot 2020-12-10 at 18 55 16" src="https://user-images.githubusercontent.com/6909106/101810603-48691700-3b19-11eb-89ad-a50e730edd3a.png">

It's easy to solve this problem, I have replaced the int function by the following:

```
def r_int(f_number):
    if f_number >= int(f_number) + 0.5:
        return int(f_number) + 1
    else:
        return int(f_number)
```

**Comment by yinguobing** [comment]
Hi @glmanhtu 

Sorry I can not reproduce this issue. According to the error message there was a mismatch of tensor shapes. Could you provide the arguments for the heatmap generation function, or the image and mark samples so I can check in detail? 

Thanks!

**Comment by glmanhtu** [comment]
Hello @yinguobing 
To reproduce the error, you can extract the files in the attachment and put it into the root folder of this project, then run the testing.py.
the image and marks in the test folder is coming from the 300vw database
[testing.zip](https://github.com/yinguobing/facial-landmark-detection-hrnet/files/5682837/testing.zip)

**Comment by yinguobing** [comment]
Confirmed, and your fix is valid. 

I think we should re-write this function.

**Comment by yinguobing** [comment]
The latest commit should resolve this issue. 
Please re-open it if not.
