### ISSUE TITLE
No module named 'face_detector.detector

### ISSUE THREAD

**Issue by Derek-Kun** [yinguobing/facial-landmark-detection-hrnet#8]
大佬你好，我发现git下面的 face_detector文件夹下面的超链接是错的，导致我运行predict.py的时候报错 ModuleNotFoundError: No module named 'face_detector.detector'， 请问能否修复一下该链接？ 非常感谢！

**Comment by yinguobing** [comment]
我又忘记push submodule了！

已修复，你再试试~

**Comment by Derek-Kun** [comment]
好的，非常感谢~
